### ISSUE TITLE
Bump Node support to 12+

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-img#100]
via dependency updates:
* `image-size` 1.x https://github.com/image-size/image-size/commit/91959a49c29bcc64038e3c632b071ce8c61ca913
* `p-queue` 7.x https://github.com/sindresorhus/p-queue/releases/tag/v7.0.0
* `fs-extra` 10.x https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#1000--2021-05-03

**Comment by zeroby0** [comment]
Looks like this is the only issue left before [1.0 milestone](https://github.com/11ty/eleventy-img/milestone/12)

Unless you have any other plans, can I start a PR for this?
