### ISSUE TITLE
Fixed length for id/hash in filenameFormat

### ISSUE THREAD

**Issue by szegheo** [11ty/eleventy-img#103]
I thought the `id` in `filenameFormat` is always a 8 characters long hash, but I've just realized that one of my files got a 7 chars length hash. 

A common situation: My web server is configured to set long cache for fingerprinted assets (generated by 11ty and Webpack) and the logic is a regexp like `\.[a-z0-9]{8}\.(exta|extb)$` to match these files.

I think it should be mentioned in the docs that the id argument is not a fixed-length hash (I assumed).

Even better would be to replace [short-hash](https://www.npmjs.com/package/short-hash) with something similar which generates a fixed-length hash (...and maybe a new option for `eleventy-img` like `hashLength`).

**Comment by coderars** [comment]
My sudden workaround for the situation:
````js
id.padEnd(8, '0').substring(0, 8) // <- fill with zeros in the end if needed, fix length to 8 chars
````

**Comment by zachleat** [comment]
You can use `filenameFormat` to customize this right?

I suppose I don’t know—is it a common assumption that hashes are a fixed length?

**Comment by zachleat** [comment]
There is a `hashLength` option, it’s new on the docs—building now!

**Comment by zachleat** [comment]
https://www.11ty.dev/docs/plugins/image/
