### ISSUE TITLE
GIF output requires libvips with support for ImageMagick

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy-img#104]
Plugin version: 0.9.0

No special configurations or anything. Just want to resize and convert an animated GIF, but I get this:

> `RenderError` was thrown
> GIF output requires libvips with support for ImageMagick

I've run into this problem before with Sharp itself, which is where I think this error is coming from (https://github.com/lovell/sharp/issues/2437). Haven't had any luck installing libvips in the past as I'm on Windows/WSL. 

I guess I answered my own question, but submitting this in case anyone has run into this in the past and has a good solution. Suppose I install libvips; should I then remove and re-install the 11ty image plugin?

**Comment by YevhenKap** [comment]
> I guess I answered my own question, but submitting this in case anyone has run into this in the past and has a good solution. **Suppose I install libvips; should I then remove and re-install the 11ty image plugin**?

Hello. Yes, it works for me.

**Comment by zachleat** [comment]
Shipping with v1.1.0 

See also https://github.com/11ty/eleventy-img/issues/139#issuecomment-1049236505
