### ISSUE TITLE
Error: Missing `sizes` attribute on eleventy-img shortcode

### ISSUE THREAD

**Issue by noelforte** [11ty/eleventy-img#107]
Followed along with the documentation at https://www.11ty.dev/docs/plugins/image/ and attempted to implement this code below:

```javascript
const Image = require("@11ty/eleventy-img");

async function imageShortcode(src, alt, sizes) {
  let metadata = await Image(src, {
    widths: [300, 600],
    formats: ["avif", "jpeg"]
  });

  let imageAttributes = {
    alt,
    sizes,
    loading: "lazy",
    decoding: "async",
  };

  // You bet we throw an error on missing alt in `imageAttributes` (alt="" works okay)
  return Image.generateHTML(metadata, imageAttributes);
}

module.exports = function(eleventyConfig) {
  eleventyConfig.addNunjucksAsyncShortcode("image", imageShortcode);
  eleventyConfig.addLiquidShortcode("image", imageShortcode);
  eleventyConfig.addJavaScriptFunction("image", imageShortcode);
};
```

However, when a build is run I get the following error in my terminal:

```shell
> Error with Nunjucks shortcode `image`

`EleventyShortcodeError` was thrown
> Missing `sizes` attribute on eleventy-img shortcode from: /img/3915eb99-300.jpeg
```

I suspect this is related to #59 and #60, but is sizes required? It doesn't seem possible to use the plugin without passing a sizes attribute to the shortcode, making this code in the docs invalid:

```nunjucks
{% image "./src/images/cat.jpg", "photo of my cat" %} <!-- Doesn't work, throws an error. -->
{% image "./src/images/cat.jpg", "photo of my cat", "(min-width: 30em) 50vw, 100vw" %} <!-- works as intended -->
```

Is this a bug? Or is this behavior intentional?

**Comment by noelforte** [comment]
Follow-up: just took a look at https://github.com/11ty/eleventy-img/blob/master/generate-html.js#L69 to see what I could find and caught the comment left there. If I'm using multiple formats I'll be sure to add in `sizes` rules.

**Comment by nhoizey** [comment]
The comment is wrong, `sizes` is required when there's a `srcset`, whatever the number of sources in it.

**Comment by noelforte** [comment]
Got it. Thanks for the clarification!

**Comment by wommy** [comment]
`sizes: 'null'` also works

**Comment by zachleat** [comment]
Of course @nhoizey  is right, I’ve updated the comments to reflect the spec:

```
// Per the HTML specification sizes is required srcset is using the `w` unit
// https://html.spec.whatwg.org/dev/semantics.html#the-link-element:attr-link-imagesrcset-4
```

Just for final clarity, we only add `srcset` when creating more than one output width, so `sizes` is required when `widths` has more than one unique value smaller than the input image width.

Thanks y’all!

**Comment by wommy** [comment]
am i crazy or is the first `<p>` is it formatted incorrectly? i just copied and pasted it

> The image[srcset attribute](https://html.spec.whatwg.org/dev/images.html#srcset-attribute) may be present, and is a srcset attribute.

vs on source

> The `imagesrcset` attribute may be present, and is a [srcset attribute](https://html.spec.whatwg.org/dev/images.html#srcset-attribute).

**Comment by wommy** [comment]
i just found [html spec multipage](https://html.spec.whatwg.org/multipage/semantics.html) which is like 100x better than [html spec dev](https://html.spec.whatwg.org/dev/semantics.html)

- https://html.spec.whatwg.org/multipage/embedded-content.html
- https://html.spec.whatwg.org/multipage/images.html

**Comment by wommy** [comment]
> Of course @nhoizey is right, I’ve updated the comments to reflect the spec:
> 
> ```
> // Per the HTML specification sizes is required srcset is using the `w` unit
> // https://html.spec.whatwg.org/dev/semantics.html#the-link-element:attr-link-imagesrcset-4
> ```
> 
> Just for final clarity, we only add `srcset` when creating more than one output width, so `sizes` is required when `widths` has more than one unique value smaller than the input image width.
> 
> Thanks y’all!

i just found [html spec multipage](https://html.spec.whatwg.org/multipage/semantics.html) which is like 100x better than [html spec dev](https://html.spec.whatwg.org/dev/semantics.html)

here you can clearly see youre referencing 
- [4 The elements of HTML](https://html.spec.whatwg.org/multipage/semantics.html#semantics)
  - [4.2 Document metadata](https://html.spec.whatwg.org/multipage/semantics.html#document-metadata)
    - [4.2.4 The link element](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element)
      - [Content attributes](https://html.spec.whatwg.org/multipage/dom.html#concept-element-attributes)
        - [imagesrcset](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-imagesrcset)

when i think 

- [4 The elements of HTML](https://html.spec.whatwg.org/multipage/#toc-semantics)
  - [4.8 Embedded content](https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content)
    - [4.8.1 The picture element](https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element)
    - [4.8.2 The source element](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element)
    - [4.8.3 The img element](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element)
    - [4.8.4 Images](https://html.spec.whatwg.org/multipage/images.html#images)
  
makes much more sense

**Comment by wommy** [comment]
> Of course @nhoizey is right, I’ve updated the comments to reflect the spec:
> 
> ```
> // Per the HTML specification sizes is required srcset is using the `w` unit
> // https://html.spec.whatwg.org/dev/semantics.html#the-link-element:attr-link-imagesrcset-4
> ```
> 
> Just for final clarity, we only add `srcset` when creating more than one output width, so `sizes` is required when `widths` has more than one unique value smaller than the input image width.
> 
> Thanks y’all!

and it seems like `sizes` are only required when following a [Device-pixel-ratio-based selection](https://html.spec.whatwg.org/multipage/images.html#introduction-3:device-pixel-ratio-2)

> If the [srcset](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-srcset) attribute has any [image candidate strings](https://html.spec.whatwg.org/multipage/images.html#image-candidate-string) using a [width descriptor](https://html.spec.whatwg.org/multipage/images.html#width-descriptor), the [sizes attribute](https://html.spec.whatwg.org/multipage/images.html#sizes-attribute) must also be present, and is a [sizes](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-sizes) attribute. The sizes attribute contributes the [source size](https://html.spec.whatwg.org/multipage/images.html#source-size-2) to the [source set](https://html.spec.whatwg.org/multipage/images.html#source-set), if the [source](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element) element is selected.
> > [Source](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-sizes)

**Comment by nhoizey** [comment]
`sizes` is indeed required for `srcset-w` but not even useful for `srcset-x`.

**Comment by wommy** [comment]
it seems like descriptors,[width](https://html.spec.whatwg.org/multipage/images.html#width-descriptor) and [pixel density](https://html.spec.whatwg.org/multipage/images.html#pixel-density-descriptor), are the second argument of [image candidate strings](https://html.spec.whatwg.org/multipage/images.html#image-candidate-string), which satisfy [srcset](https://html.spec.whatwg.org/multipage/images.html#srcset-attributes)

learning alot today,

i still think the generated picture can be optimized further

**Comment by zachleat** [comment]
> i still think the generated picture can be optimized further

@wommy Feel free to open another issue with suggestions!

**Comment by wommy** [comment]
yeah i definitely will whenever i get the time <3 thanks for all your hard work fellas
