### ISSUE TITLE
Allow for nested directories within `outputDir`.

### ISSUE THREAD

**Issue by jgerigmeyer** [11ty/eleventy-img#112]
We use nested directories for our src images (e.g. `src/images/blog/foobar.jpg` and `src/images/projects/foobar.jpg`), and ideally we'd like to maintain that nested directory structure in our processed images (e.g. `_site/img/blog/foobar-300w.webp` and `_site/img/projects/foobar-300w.webp`) so we can use a custom `filenameFormat` without overriding images that have the same name.

It seems that returning a path from the `filenameFormat` option doesn't work, so I assume this use-case isn't supported. Is this something you'd consider adding in the future?

In the meantime, we're appending the hash `id` to our custom filename, to prevent duplicate filenames from overriding one another. It might be worth adding this (and/or a note about the potential issue) to the example docs?

```js
const path = require("path");
const Image = require("@11ty/eleventy-img");

await Image("./test/bio-2017.jpg", {
  widths: [300],
  formats: [null],
  filenameFormat: function (id, src, width, format, options) {
    const extension = path.extname(src);
    const name = path.basename(src, extension);

    return `${name}-${width}w-${id}.${format}`;
  }
});

// Writes: "test/img/bio-2017-300w-a12b1234.jpeg"
```

Thanks for a great plugin!

**Comment by zachleat** [comment]
Hmm, you should be able to change the `outputDir` option based on the input path, no?

**Comment by jgerigmeyer** [comment]
> Hmm, you should be able to change the `outputDir` option based on the input path, no?

D'oh! 🤦 Thanks for the suggestion; that works fine. 👍

**Comment by zachleat** [comment]
Great! glad to hear it!

**Comment by zachleat** [comment]
There also is a `urlFormat` option hiding in there if you’re willing to dig deep enough (needs to be documented)

Filed https://github.com/11ty/eleventy-img/issues/113

**Comment by jgerigmeyer** [comment]
In case it helps others who find this issue, this is my approach for maintaining source image nested directories:

```js
const path = require("path");
const Image = require("@11ty/eleventy-img");

const defaultOpts = {
  widths: [300],
  formats: ['webp'],
  filenameFormat: function (id, imgSrc, width, format, options) {
    const extension = path.extname(imgSrc);
    const name = path.basename(imgSrc, extension);

    return `${name}-${width}w.${format}`;
  }
};
const IMG_SRC = './src/images/';

const image = (src) => {
  let outputDir = './_site/assets/images/';
  let urlPath = '/assets/images/';
  if (src.startsWith(IMG_SRC)) {
    const dir = path.dirname(src.slice(IMG_SRC.length));
    outputDir = `${outputDir}${dir}`;
    urlPath = `${urlPath}${dir}`;
  } else {
    console.warn(`Unexpected image source path: "${src}"`);
  }

  const opts = {
    ...defaultOpts,
    outputDir,
    urlPath,
  };

  await Image(src, opts);
};

image("./test/bio-2017.jpg");
```

**Comment by davidrhoden** [comment]
I need to do what you're doing (nested directories in image paths, but this doesn't work for me. I get an error on "await": 

`SyntaxError: await is only valid in async function`

Maybe I'm missing the part where you begin an async function. I put all this code in `eleventy.js`. Does some of it belong elsewhere?

**Comment by jgerigmeyer** [comment]
> `SyntaxError: await is only valid in async function`

@davidrhoden Sorry, my mistake. Edited to add `async` definition.

> I put all this code in `eleventy.js`. Does some of it belong elsewhere?

Sure, that works. I added a shortcode for it so I could use it in my templates too, but that's up to you.
