### ISSUE TITLE
Lossy/lossless compression?

### ISSUE THREAD

**Issue by aaronpeters** [11ty/eleventy-img#12]
Hi,

This plugin looks great!
Only thing I would love to see added is image compression (e.g. set PNG and/or JPG quality to 80).
Is that on the roadmap?

**Comment by tanc** [comment]
I think at the moment 80 is the default quality that sharp uses when preparing images.

**Feature request:** I'd like to be able to pass in a quality number as an option so I can define the quality myself

**Comment by zachleat** [comment]
Howdy y’all! We shipped this awhile back, docs are here for the different output formats: https://www.11ty.dev/docs/plugins/image/#advanced-control-of-sharp-image-processor
