### ISSUE TITLE
If null happens to coincide with one of the image widths or formats passed in, duplicate copies are generated

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [11ty/eleventy-img#124]
Steps to reproduce:

1. Invoke the image plugin with the following source image (400px wide): https://images.unsplash.com/photo-1591160690555-5debfba289f0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80
2. Specify `[null, 400]` for the `widths` option.
3. Observe that the output JSON contains two 400-width images in the array.

This causes an issue on my site where an image is listed twice in the markup:

![image](https://user-images.githubusercontent.com/19352442/132019707-9b42feb7-e073-401f-91c6-d948021ac4bf.png)

Also reproducible if:

1. You replace `null` with `400`: `[400, 400]`.
2. You pass in duplicate formats, like `[null, 'png']` when the original format is `png`.

Expected behavior: The final widths/formats passed to the plugin should be unique. If a width/format happens to coincide with the source image width/format (`null`), only one copy should be returned.

Would be happy to contribute a PR (assuming this is in fact a bug and not the intended behavior)

**Comment by AleksandrHovhannisyan** [comment]
Bump, just wanna make sure this is at least on someone's radar 😄

**Comment by zachleat** [comment]
Appreciate this one, thank you!
