### ISSUE TITLE
Sets output image dimensions to largest available

### ISSUE THREAD

**Issue by schwigri** [11ty/eleventy-img#129]
I currently have a shortcode setup like this:

    eleventyConfig.addNunjucksAsyncShortcode(
      "image",
      async (source, alt, width) => {
        const src = source.startsWith("http") ? source : `./src/images/${source}`;
        const widths = width ? [width, width * 2] : [];
        const metadata = await Image(src, {
          formats: ["avif", "webp", "jpg"],
          outputDir: "./_site/img",
          widths,
        });

        const imageAttributes = {
          alt,
          decoding: "async",
          loading: "lazy",
          sizes: "100vw",
        };

        return Image.generateHTML(metadata, imageAttributes, {
          whitespaceMode: "inline",
        });
      }
    );

So, in Eleventy Nunjucks template I use like this:

    {{ image "image.jpg", "Alt text", 500 }}

If my image is a square, I would expect output to have width and height of 500. However, the output `img` tag has a width and height of 1000, so the image is twice as large as I want it to display.

How can I fix this, or force to be the smaller width?

**Comment by zachleat** [comment]
I’m still not sold on this one but I will place it in the enhancement queue for folks to vote on it.

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-img/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
`fallback` option shipping with v6.0.0-beta.1 #265
