### ISSUE TITLE
Multiple pass image encoding

### ISSUE THREAD

**Issue by djmtype** [11ty/eleventy-img#13]
I think the images are encoded using the optimized baseline. This is great for small images. A nice enhancement would be the ability to choose how the image gets encoded. For example, loading large images in multiple passes would be my preference, so at least users on slow connections would see some resemblance of an image start to load immediately.

**Comment by zachleat** [comment]
Can you be more specific? Are you referencing progressive JPEG or PNG?

**Comment by djmtype** [comment]
@zachleat More so for JPEGs. I think you're using Sharp? If you look at the `options.progressive` parameter in the docs [https://sharp.pixelplumbing.com/api-output](https://sharp.pixelplumbing.com/api-output), that's what I mean.

**Comment by sparkalow** [comment]
Sharp's options for various api methods are quite useful and diverse. I wonder if allowing setting sharp options via some sort of passthrough would be worth it.

**Comment by zachleat** [comment]
We have this now! https://www.11ty.dev/docs/plugins/image/#advanced-control-of-sharp-image-processor

Thanks!
