### ISSUE TITLE
Skip image processing with eleventy-img - raw image?

### ISSUE THREAD

**Issue by alvarotrigo** [11ty/eleventy-img#133]
I have some images on the blog posts that are on the .md file on the layout front matter as images to use for sharing in social media and as a thumbnail.

Those images still need to be moved to the `_site` folder and I would like to move them only once and only if they change.
That's why I considered using `eleventy-img` for them instead of just using `fs.copyFile`.

I want to make use of the  `eleventy-img`  cache for this but i don't want  `eleventy-img`  to process them at all.
They are in png and for some reason  `eleventy-img`  ends up creating a bigger file.

Source file 5.9Kb and output file is 7.7Kb. 
Both png.

Is there a way to tell  `eleventy-img`  we want to skip any kind of image processing?

I tried using `sharOptions` to pass the [`raw` option](https://sharp.pixelplumbing.com/api-output#raw), but it doesn't seem to do the trick:

```js
                await Image(src, {
			formats: ["png"],
			outputDir: outputDir,
			useCache: false,
			sharOptions: {
				raw: true
			},

			// Define custom filenames for generated images
			filenameFormat: function (id, src, width, format, options) {
				const name = path.basename(src, format);

				return `${name}${format}`;
			}
		})

```

**Comment by zeroby0** [comment]
https://www.11ty.dev/docs/plugins/image/#output-widths
> `widths: [null]` (default, keep original width)

That should skip processing the images. 

Another option is to write your own shortcode with fs.copyFile, but don't copy if `eleventy-img.getHash()` returns the same hash. 

-----
Also, maybe we can check internally if the output file size is larger, and print a warning or not transform the file if the dimensions don't change.

Assuming this isn't a known bug, I encourage you to report it on the sharp repo.

**Comment by zachleat** [comment]
Hmm, I think this would request be better invested in incremental build support, which already works with passthroughCopy

https://www.11ty.dev/docs/usage/incremental/#passthrough-copy

Note the pretty hefty limitation right now that incremental builds require a full build on cold start https://www.11ty.dev/docs/usage/incremental/#cold-start https://github.com/11ty/eleventy/issues/984

Given that information, I will still put this on the enhancement queue for upvotes but (imo) the muscle would be better spent on improving incremental build support.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-img/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Related to #212

**Comment by zachleat** [comment]
Let’s regroup on #212 for this one!

**Comment by zachleat** [comment]
Shipping with v7.0.0-alpha.5 more info at #212.
