### ISSUE TITLE
Allow to specify width AND height

### ISSUE THREAD

**Issue by mahnunchik** [11ty/eleventy-img#134]
Allow to specify width AND height to resize and crop to specific dimensions.

```js
const metadata = await Image(src, {
  sizes: [{ width: 300, height: 200 }, { width: 600, height: 400} ],
  formats: ["avif", "jpeg"]
});
```

As on option the same result may be obtained by specifying `aspect ratio`.

**Comment by mahnunchik** [comment]
Related: https://github.com/11ty/eleventy-img/issues/31

**Comment by AleksandrHovhannisyan** [comment]
(Might be worth just posting this code in #31 as a suggested API so we only have one ticket for it)

**Comment by zachleat** [comment]
Yeah let’s organize over at #31 for this. I do like your sample code!
