### ISSUE TITLE
[PATCH-PACKAGE] Prevent images from being rotated if the original contains EXIF orientation metadata

### ISSUE THREAD

**Issue by jdvivar** [11ty/eleventy-img#135]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@11ty/eleventy-img@1.0.0` for the project I'm working on.

#93

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@11ty/eleventy-img/img.js b/node_modules/@11ty/eleventy-img/img.js
index 97ec5f5..9e6eee8 100644
--- a/node_modules/@11ty/eleventy-img/img.js
+++ b/node_modules/@11ty/eleventy-img/img.js
@@ -434,7 +434,7 @@ class Image {
           if(metadata.format !== "svg" || !this.options.svgAllowUpscale) {
             resizeOptions.withoutEnlargement = true;
           }
-          sharpInstance.resize(resizeOptions);
+          sharpInstance.rotate().resize(resizeOptions);
         }
 
         if(!this.options.dryRun) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chrissy-dev** [comment]
I need this 🥇 💯

**Comment by zachleat** [comment]
The merge from #132 fixes this and will ship with 1.1.0

**Comment by jdvivar** [comment]
Great, thanks @zachleat

**Comment by chrissy-dev** [comment]
Nice one @zachleat 👍🏼
