### ISSUE TITLE
Remote image outputs [object Promise]

### ISSUE THREAD

**Issue by jacob-rh** [11ty/eleventy-img#152]
Hi there,

I'm trying to use eleventy-img as a shortcode to output CMS images. 

I've just used the sample code from the docs for now.

.eleventy.js looks like:
```
...
const Image = require('@11ty/eleventy-img');

async function imageShortcode(src, alt, sizes) {
    console.log('image', {src, alt, sizes});
    
    let metadata = await Image(src, {
        outputDir: './src/img',
        widths: [300, 600],
        formats: ["avif", "jpeg"]
    });
  
    let imageAttributes = {
        alt,
        sizes,
        loading: "lazy",
        decoding: "async",
    };
  
    // You bet we throw an error on missing alt in `imageAttributes` (alt="" works okay)
    return Image.generateHTML(metadata, imageAttributes);
}

module.exports = function (eleventyConfig) {
    ...
    eleventyConfig.addNunjucksShortcode('image', imageShortcode);

    ...
    eleventyConfig.addPassthroughCopy('./src/img');

    return {
        dir: {
		input: 'src',
		output: 'dist'
	},
        templateFormats: ['html', 'md', 'njk'],
        passthroughFileCopy: true
    };
```

The console log in the shortcode function shows: 
```
image {
  src: 'http://headless-test.local/wp-content/uploads/2022/05/luca-bravo-SRjZtxsK3Os-unsplash-scaled.jpg',
  alt: '',
  sizes: '(min-width: 30em) 50vw, 100vw'
}
```

page.njk then contains:
```
{% if heroImage != false %}
    {% image heroImage.url, heroImage.alt, "(min-width: 30em) 50vw, 100vw" %}
{% endif %}
```

When I run `npx @11ty/eleventy --serve` the build runs fine and the images are generated correctly in the right folders. 

But the output in the generated html (where the image should be) is `[object Promise]` .. Just wondering why this might be?

I've tried getting help on discord but the person who tried to help was also left scratching their head.

**Comment by pdehaan** [comment]
I haven't tried recreating this locally, but it might be an async issue where you need to use `.addNunjucksAsyncShortcode()` instead of `.addNunjucksShortcode()` since the method is async?

https://www.11ty.dev/docs/languages/nunjucks/#asynchronous-shortcodes

**Comment by jacob-rh** [comment]
Amazing! That's done it. Thank you @pdehaan. 

Apologies for not looking through the 11ty docs more thoroughly for a solution. 

It might be worth adding mention of `. addNunjucksAsyncShortcode()` to the official eleventy-image documentation?

**Comment by zachleat** [comment]
addShortcode is async-friendly in v2.0.0+ so this hopefully shouldn’t trip folks up. Thanks y’all!
