### ISSUE TITLE
having trouble getting disk cache to work

### ISSUE THREAD

**Issue by btrem** [11ty/eleventy-img#161]
Note: copied from https://github.com/11ty/eleventy/discussions/2619 on the advice of https://github.com/11ty/eleventy/discussions/2619#discussioncomment-4010601.

I'm using 11ty/image. Each time I run 11ty --serve, all of my images are reprocessed, making the initial build time very slow. According to https://www.11ty.dev/docs/plugins/image/#disk-cache, this shouldn't happen.

    Eleventy will skip processing files that are unchanged and already exist in the output directory.

Issue #51 seems to indicate that persisting the cache to disk has been added to image as of 1.0.0. Is there something I need to do to my async image function to enable the disk cache feature?

**Comment by zeroby0** [comment]
Are you deleting the output folder by any chance? Usually it happens by `rm -rf` or `rimraf` ing the 11ty output directory in package.json, which also contains the cached eleventy_img images.

**Comment by btrem** [comment]
No. I never run the `clean` or `production` script (so never `rm -rf`).

**Comment by btrem** [comment]
Ouf. Just checked image file dates, and it turns out it is *not* regenerating images every time. There is apparently something else which is slowing down my initial run.

Apologies to all.

**Comment by zeroby0** [comment]
Happens, don't worry about it :)
