### ISSUE TITLE
Implement option to switch set of formats on transparency

### ISSUE THREAD

**Issue by Snapstromegon** [11ty/eleventy-img#163]
I want to build an image shortcode that does not output jpgs when the input image is/(might be) using transparency and instead use pngs.
Since the documentation points out that relying on the file extension isn't correct, I'd love to use the metadata sharp exposes to make this decision.

Right now I use it something like this:

```
Image(src, {
  widths: [256, 512, 1024, null],
  formats: [
    "avif",
    "webp",
    src.toLowerCase().endsWith(".png") ? "png" : "jpeg",
  ],
  outputDir: "_site/img/",
});
```

I don't know what the most elegant way of doing this would be, but I think such a feature would help more people than jsut me.

**Comment by terpimost** [comment]
@Snapstromegon thank you for a solution. 

In my case attempt of producing jpeg image out of png just doesn't provide correct image at all, so it looks like a lost picture.

**Comment by zachleat** [comment]
A bunch of discussion on this one already at https://github.com/11ty/eleventy-img/issues/105
