### ISSUE TITLE
Question: How do I properly render an image using the sample code and Nunjucks?

### ISSUE THREAD

**Issue by kaeside** [11ty/eleventy-img#17]
Hi everyone,

I was wondering if anyone could be of assistance with helping me understand how this is implemented.

I'm currently working off Eleventail provided by Phil Hawksworth: https://github.com/philhawksworth/eleventail

I'm learning how to use eleventy-img by attempting to replace the existing possum image on the index page with one rendered by eleventy-img.

I'm using nunjucks for this and I'm using only two arguments: the img path and the alt copy.

I'm also using the sample code from the readme but instead of using `addJavaScriptFunction`, I'm using `addNunjucksAsyncShortcode`.

I'm receiving a message in my console stating that the Input file is missing, however this is the same img src as what is in the the original code that is working.

Am I not properly referencing the image file path?

I was going to ask this on @stedman issue, but I didn't want to pollute that issue with my question.

I'm pretty sure this is something I'm either missing or not understanding.

Regards,
Kaeside

```
# index.njk
...
<div>
    ...
    {% myResponsiveImage "/images/possum-balloon.png", "possum" %}
    ...
</div>
...
```

```
# eleventy,js

...
eleventyConfig.addNunjucksAsyncShortcode("myResponsiveImage", async function (src, alt, options) {
    if (alt === undefined) {
      // You bet we throw an error on missing alt (alt="" works okay)
      throw new Error(`Missing \`alt\` on myResponsiveImage from: ${src}`);
    }

    let stats = await Image(src, options);
    let lowestSrc = stats.jpeg[0];
    let sizes = "100vw"; // Make sure you customize this!

    // Iterate over formats and widths
    return `<picture>
      ${Object.values(stats).map(imageFormat => {
      return `  <source type="image/${imageFormat[0].format}" srcset="${imageFormat.map(entry => `${entry.url} ${entry.width}w`).join(", ")}" sizes="${sizes}">`;
    }).join("\n")}
        <img
          alt="${alt}"
          src="${lowestSrc.url}"
          width="${lowestSrc.width}"
          height="${lowestSrc.height}">
      </picture>`;
  });
...
```

```
`TemplateContentRenderError` was thrown
> (./src/site/index.njk)
  EleventyShortcodeError: Error with Nunjucks shortcode `myResponsiveImage`

`Template render error` was thrown
> Input file is missing
```

**Comment by stedman** [comment]
@kaeside what do your [options](https://github.com/11ty/eleventy-img#options-list) look like? Does the following help?

```js
const options = {
  ...
  urlPath: "/images/",
  outputDir: "dist/images/",
  ...
};
```
If that doesn't work, try temporarily switching the shortcode and `index.njk` to LiquidJS. I recall hitting a wall with async Nunjucks and I think it was related to this.

**Comment by kaeside** [comment]
Hey @stedman! Thanks for the quick response.

Where are you declaring your options? 
Are you passing it in on a per image basis, declaring it at the top of eleventy.js, or is this an object within the async callback for addNunjucksAsyncShortcode in the eleventy.js file? 

For testing purposes I'm declaring it within the aforesaid async callback.

My options object is the following:

```
eleventyConfig.addNunjucksAsyncShortcode("myResponsiveImage", async function (src, alt, options) {
...
const options = {
  widths: [null],
  formats: ["png"], 
  urlPath: "src/site/images/",
  outputDir: "dist/images/",
  cacheOptions: {
    duration: "1d",
    directory: ".cache",
    removeUrlQueryParams: false,
  }
}
...
}
```

**Comment by treb0r** [comment]
@kaeside I am seeing exactly the same error when I try to recreate the example in a Nunjucks template.

A working Nunjucks example would be a huge help for those of us who are struggling to use this plug-in to transform our images at build time.

**Comment by stedman** [comment]
@kaeside in my case, [I set the options in a shortcode module](https://github.com/austinjavascript/austinjavascript.com/blob/master/_includes/shortcodes/avatar.js#L11-L22).

Your code might look like the following:

```js
// eleventy.js //

...
eleventyConfig.addNunjucksAsyncShortcode("myResponsiveImage", async function (src, alt) {
    if (alt === undefined) {
      // You bet we throw an error on missing alt (alt="" works okay)
      throw new Error(`Missing \`alt\` on myResponsiveImage from: ${src}`);
    }

    let stats = await Image(src, {
        widths: [null],
        formats: ["png"], 
        urlPath: "src/site/images/",
        outputDir: "dist/images/",
        cacheOptions: {
          duration: "1d",
          directory: ".cache",
          removeUrlQueryParams: false,
        }
      });
    let lowestSrc = stats.jpeg[0];
    let sizes = "100vw"; // Make sure you customize this!

    // Iterate over formats and widths
    return `<picture>
      ${Object.values(stats).map(imageFormat => {
      return `  <source type="image/${imageFormat[0].format}" srcset="${imageFormat.map(entry => `${entry.url} ${entry.width}w`).join(", ")}" sizes="${sizes}">`;
    }).join("\n")}
        <img
          alt="${alt}"
          src="${lowestSrc.url}"
          width="${lowestSrc.width}"
          height="${lowestSrc.height}">
      </picture>`;
  });
...
```

**Comment by andrewjireland** [comment]
I'm also seeing the same ```> Input file is missing``` error. I've tried every possible permutation for the in urlPath I can think of to no avail (assuming that's the issue).

Currently i'm trying to do the following based on @stedman's Nunjucks shortcode he gratiously provided. Can anyone see where I'm going wrong? 

Using ```@11ty/eleventy": "^0.10.0```

```javascript
// template-page.njks //
{% myImage "/images/test.jpg", "the alt text" %}
```

```javascript
// eleventy.config.js //
const Image = require("@11ty/eleventy-img");

module.exports = eleventyConfig => {
    eleventyConfig.addNunjucksAsyncShortcode("myImage", async function (src, alt, outputFormat = "jpeg") {
      if (alt === undefined) {
        // You bet we throw an error on missing alt (alt="" works okay)
        throw new Error(`Missing \`alt\` on myImage from: ${src}`);
      }

      let stats = await Image(src, {
          widths: [null],
          formats: [outputFormat], 
          urlPath: "/images/", // also tried /site/images/
          outputDir: "dist/images/",
        });
      let lowestSrc = stats.jpeg[0];
      let sizes = "100vw"; // Make sure you customize this!

      // Iterate over formats and widths
      return `<picture>
        ${Object.values(stats).map(imageFormat => {
        return `  <source type="image/${imageFormat[0].format}" srcset="${imageFormat.map(entry => `${entry.url} ${entry.width}w`).join(", ")}" sizes="${sizes}">`;
      }).join("\n")}
          <img
            alt="${alt}"
            src="${lowestSrc.url}"
            width="${lowestSrc.width}"
            height="${lowestSrc.height}">
        </picture>`;
    });  
    

    return {
        templateFormats: ["md", "njk"],
        markdownTemplateEngine: 'njk',
        htmlTemplateEngine: 'njk',
        passthroughFileCopy: true,

        dir: {
            input: 'site',
            output: 'dist',
            includes: 'includes',
            data: 'globals'
        }
    }

}
```

![image](https://user-images.githubusercontent.com/18650897/89514031-a9ee4180-d818-11ea-96d7-fa33a4c25c5c.png)

**Comment by sachinsancheti1** [comment]
i have tried all the combinations on the thread above and i face exactly the same issues. Hope to hear on this.

**Comment by stedman** [comment]
@kaeside et al, I was able to replicate your `Input file is missing` issue and find a fix. 

Make sure that your shortcode image paths include the full path from the root of the project. For example:

```
// index.njk //
...
<div>
  {% myResponsiveImage "./src/site/images/possum-balloon.png", "possum" %}
</div>
...
```

I also noticed another issue with the `stats` property used to set the `lowestSrc` variable. Since the output format was changed from `jpeg` to `png`, you will also need to update that in the `let lowesSrc = stats.jpeg[0];` line.

```js
// .eleventy.js //
...
  eleventyConfig.addNunjucksAsyncShortcode("myResponsiveImage", async function (src, alt) {
    if (alt === undefined) {
      // You bet we throw an error on missing alt (alt="" works okay)
      throw new Error(`Missing \`alt\` on myResponsiveImage from: ${src}`);
    }

    let outputFormat = "png";
    let stats = await Image(src, {
        widths: [null],
        formats: [outputFormat],
        urlPath: "/images/",
        outputDir: "dist/images/",
        cacheOptions: {
          duration: "1d",
          directory: ".cache",
          removeUrlQueryParams: false,
        }
      });
    let lowestSrc = stats[outputFormat][0];
    let sizes = "100vw"; // Make sure you customize this!

    // Iterate over formats and widths
    return `<picture>
      ${Object.values(stats).map(imageFormat => {
      return `  <source type="image/${imageFormat[0].format}" srcset="${imageFormat.map(entry => `${entry.url} ${entry.width}w`).join(", ")}" sizes="${sizes}">`;
    }).join("\n")}
        <img
          alt="${alt}"
          src="${lowestSrc.url}"
          width="${lowestSrc.width}"
          height="${lowestSrc.height}">
      </picture>`;
  });
...
```

I'll take a look at this again tomorrow and open a PR to help the documentation.

**Comment by kaeside** [comment]
Thanks so much @stedman! 

I was taking a crack at it this evening (lost power for a few days due to a storm) 

I was trying to make it work by creating the imgGen in my ` _data` directory so that I can make the images available as global variables.

something like:

```
...
asyncImgGenFn(arg1, arg2)
...

module.exports = {
  "img1": asyncImgGenFn(imgPath, imgAltCopy),
  "img2": asyncImgGenFn(imgPath, imgAltCopy)
}
```

But your solution has worked for me! 

Thanks!
