### ISSUE TITLE
slow initial build time

### ISSUE THREAD

**Issue by btrem** [11ty/eleventy-img#170]
My initial build time when I use 11th-img with --serve is really slow, even though all the images are already on the disk and I've enabled disk cache:

```[11ty] Copied 26 files / Wrote 295 files in 350.65 seconds (1188.6ms each, v1.0.2)```

Incremental builds while the server is running are fine:

```[11ty] Copied 26 files / Wrote 295 files in 1.61 seconds (5.5ms each, v1.0.2)```

If I skip the image processing, the initial build is lightning fast:

```[11ty] Copied 26 files / Wrote 295 files in 2.97 seconds (10.1ms each, v1.0.2)```

Is that normal? Does 11ty-img need to load every image from disk into memory? If I'm doing something wrong, are there tools to figure out where the bottleneck lies?

**Comment by zeroby0** [comment]
Should only be slow on the first ever build. It reads all the images, processes them, and saves the processed images to the output folder.

As long as the processed image exists in the output folder, it will not be processed again. A common pitfall is when you delete the output folder, say maybe in an npm script on build.

If you can make a repository that reproduces this behaviour with minimum code, I'll be happy to help you debug.

**Comment by btrem** [comment]
I'm not deleting the folder. (I can see images dated weeks or months in the past.)

Thanks for offering to help. I'll pare down my 11ty site folder and create a github repo. Or maybe I'll figure it out when I pare things down, in which case I'll reply here what the problem was.

**Comment by btrem** [comment]
@zeroby0 : I created a repo of a pared down version of my site, available here:

https://github.com/btrem/11ty_img_test

The repo doesn't include the .jpeg files. Should I add them to the repo? Or would you rather I put them on Dropbox? (I think it is normal to not include binary files like bitmap images in a git repo.)

**Comment by btrem** [comment]
Initial build of pared down test site:

```[11ty] Copied 1 file / Wrote 46 files in 97.17 seconds (2112.4ms each, v1.0.2)```

Build time for incremental build after modifying a .md file:

```[11ty] Copied 1 file / Wrote 46 files in 0.14 seconds (3.0ms each, v1.0.2)```

Initial build time without processing images (by returning from the `pictureShortcode` function before running `image`):

```[11ty] Copied 1 file / Wrote 46 files in 0.26 seconds (5.7ms each, v1.0.2)```

Build time for incremental build after modifying a .md file, without processing images:

```[11ty] Copied 1 file / Wrote 46 files in 0.17 seconds (3.7ms each, v1.0.2)```

**Comment by btrem** [comment]
PR #172 makes a dramatic difference:

```[11ty] Copied 1 file / Wrote 46 files in 6.95 seconds (151.1ms each, v2.0.0-canary.33)```

**Comment by zachleat** [comment]
#172 is shipping with Eleventy Image v3.0.0—thank you!
