### ISSUE TITLE
Opportunity to collaborate?

### ISSUE THREAD

**Issue by Snugug** [11ty/eleventy-img#19]
Hey! I've written a very similar plugin that we're using on our production site, [Eleventy Plugin Local Respimg](https://github.com/chromeos/static-site-scaffold-modules/tree/master/modules/eleventy-plugin-local-respimg). I'm curious if there's an opportunity to collaborate on a single solution here!

**Comment by zachleat** [comment]
That would be awesome!

**Comment by Snugug** [comment]
Fantastic!

What's the best way for you to hash that out? A video chat? Just enumerating them here? I'm pretty flexible.

**Comment by zachleat** [comment]
We had a lovely chat so I’m closing this? 😅 Feel free to file more issues with future tasks!

**Comment by Snugug** [comment]
Yah, sgtm!
