### ISSUE TITLE
Images get darker when resized

### ISSUE THREAD

**Issue by GHF** [11ty/eleventy-img#196]
I had some issues with images getting darker when downsampled, which I suspected (and mostly confirmed) was due to sharp's default pipeline being non-colorspace/gamma-aware.

Downsampling the [Eric Brasseur test image](http://www.ericbrasseur.org/gamma.html) from this:
![gamma_2.2.jpg](https://github.com/11ty/eleventy-img/assets/38979/4321f10a-e0c0-465e-9e50-4fa8506cb03b)

to 50% produces this:
![bad](https://github.com/11ty/eleventy-img/assets/38979/159761e1-c83b-487d-a319-d3db698bc545)

when I enable sharp's [linear 16-bit depth color pipeline](https://sharp.pixelplumbing.com/api-colour#pipelinecolourspace), I get very minor changes. But when I _also_ use the `gamma()` call with default parameters, I get this result, which looks much better:
![good](https://github.com/11ty/eleventy-img/assets/38979/235bd3b8-7212-49d7-9b66-6b6b4d95a6e8)

My experience is that performing additional de-gammaing should _not_ be needed after the colors have already been transformed from the input colorspace to linear RGB. So the fact that the `gamma()` call is required seems fishy because it suggests sharp's input pipeline isn't doing that colorspace conversion.

**Comment by zachleat** [comment]
I think this is probably something that we’ll extend via #52 to allow folks to do custom Sharp processing pre-output.

Independently, it might be good to file this upstream on the Sharp repository. Is this related? https://github.com/lovell/sharp/issues/3273

Please subscribe to #52!
