### ISSUE TITLE
`errorOnFail` option if you don’t want to fail the entire build if one image has an error.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-img#225]
Default to `true`.

**Comment by zachleat** [comment]
Via the image transform maybe an `eleventy:optional` attribute that will remove remote images that fail.

The impetus use case here is build-time opencollective avatar images on 11ty.dev

**Comment by eaton** [comment]
This has been important for a project with many *old* image references pointing out to external sites. eleventy-img handles 404s pretty gracefully, but on occasion encounters references to domains that won't even resolve — bringing the whole build down. Being able to sidestep that issue and proceed with the build with be a huge benefit.

**Comment by zachleat** [comment]
Milestoning to 6.0.0

**Comment by zachleat** [comment]
Important reference to #252 which unlocks the use of native fetch and AbortSignal for timeouts https://github.com/11ty/eleventy-fetch/releases/tag/v5.0.0

**Comment by zachleat** [comment]
Shipping with v6.0.0-beta.1

**Comment by zachleat** [comment]
Moving `eleventy:optional` attribute to #259
