### ISSUE TITLE
Not compatible with 11ty 2.0.11?

### ISSUE THREAD

**Issue by MartinDM** [11ty/eleventy-img#229]
I'm trying to use this plugin to allow images in posts, but when I build my project I'm shown the below error indicating the plugin is **not compatible**...but I have the latest stable of 11ty at **2.0.11.**

<img width="1166" alt="image" src="https://github.com/11ty/eleventy-img/assets/7467069/910ff07c-f36e-4afa-877c-c22d7288f5ee">

Plaintext:
Eleventy CLI Fatal Error:
[11ty] 1. Error processing the `eleventyImageTransformPlugin` plugin (via EleventyPluginError)
[11ty] 2. [@11ty/eleventy-img] `eleventyImageTransformPlugin` is not compatible with this version of Eleventy. You will need to use v3.0.0 or newer. (via Error)
[11ty] 
**[11ty] Original error stack trace: Error: [@11ty/eleventy-img] `eleventyImageTransformPlugin` is not compatible with this version of Eleventy. You will need to use v3.0.0 or newer.**

Ideally I'd not want to need a plugin to include images, but I understand to include _local_ images we need the `eleventy-img` plugin?

Thanks for any assistance on using this, as I must be doing something wrong as I'm all up to date!

**Comment by finngreig** [comment]
Also having the exact same issue here - glad to know it's not just me

**Comment by zachleat** [comment]
The image plugin *is* compatible, but the transform and on-request features require 3.0+. Read more: https://www.11ty.dev/docs/plugins/image/#eleventy-transform 3.0 alpha’s are out now and our first beta is coming soon, stay tuned!

If you’re using Eleventy v2.0, you can use this approach: https://www.11ty.dev/docs/plugins/image/#nunjucks-liquid-javascript-(asynchronous-shortcodes)

But I’d first note that `eleventy-img` is not required for images in Eleventy—it’s only used to _optimize_ images. If you just want to use a plain un-optimized image in your project, use passthrough copy https://www.11ty.dev/docs/copy/

**Comment by nfriedly** [comment]
I think the correct answer here is to install the previous version: `npm i @11ty/eleventy-img@3`

(Also, that error message is kind of confusing because it's not specifying which thing you need 3.0.0 of, especially right now eleventy v3.0.0 doesn't exist yet. Although, in this case it could just drop the ".0.0 or newer" at the end and it'd be correct either way - either upgrade eleventy to 3.x or downgrade eleventy-img to 3.x!")
