### ISSUE TITLE
"Eleventy Transform" recommended in docs but not possible to use?

### ISSUE THREAD

**Issue by alexdmiller** [11ty/eleventy-img#232]
I installed 11ty according to the documentation in the [Getting Started](https://www.11ty.dev/docs/) page. I then followed the instructions for [Eleventy Transform](https://www.11ty.dev/docs/plugins/image/#eleventy-transform) to transform images in my templates (which is marked as "recommended").

However, when I copy and paste the example code, I get this error message:

```
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error processing the `eleventyImageTransformPlugin` plugin (via EleventyPluginError)
[11ty] 2. [@11ty/eleventy-img] `eleventyImageTransformPlugin` is not compatible with this version of Eleventy. You will need to use v3.0.0 or newer. (via Error)
```

I tried updating my `package.json` to update the version of 11ty:

```
"@11ty/eleventy": "^3.0.0",
```

Then I ran `npm install`. But I got the following error message:

```
npm install
npm error code ETARGET
npm error notarget No matching version found for @11ty/eleventy@^3.0.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

I'm confused about how to use this recommended feature if it is not supported in the main release? And if it is not supported in the main release, I don't know how to use the release where it is supported.

Thank you!

**Comment by zachleat** [comment]
We’re nearing the finish line of 3.0 but you can use `npm install @11ty/eleventy@canary` to try out a pre-release! They’re pretty stable I use them on 11ty.dev 👀

https://www.11ty.dev/blog/canary-eleventy-v3/
