### ISSUE TITLE
Control over ICC profiles

### ISSUE THREAD

**Issue by pcarrier** [11ty/eleventy-img#244]
sharp exposes `keepIccProfile`, which is important to retain all the colors of Display-P3 and AdobeRGB images.

For example, check out the intensity of the green on the signage and table @ https://nothing.pcarrier.com/posts/riviere-des-parfums/ compared to the (linked) original images.
If your display supports significantly more than sRGB, the difference should be notable.

**Comment by zachleat** [comment]
Enabled by #52, shipping soon with v6.0.0-beta.1

If you think we should change the default in Eleventy Image, please let me know!

**Comment by ScreenDream** [comment]
+1 I would vote to keep ICC profiles as default.

**Comment by zachleat** [comment]
`.keepIccProfile()` will be enabled by default in Eleventy Image v6.0.0-beta.1
