### ISSUE TITLE
Diacritics and spaces seem not usable in file names

### ISSUE THREAD

**Issue by Lamecarlate** [11ty/eleventy-img#253]
Hello!

I want to use this plugin, and I'm stuck… Because I have

> ENOENT: no such file or directory

for every image with a space or an accented character in its name.

It seems the name is encoded on one end, but I fail to find which.

`![Cool beach](<Beach wallpaper - by Glater.jpeg>)` 

fires the error

> Error: ENOENT: no such file or directory, stat 'src/pages/carnet/2024/20240705.île-de-myst-en-lego/Beach%20wallpaper%20-%20by%20Glater.jpeg'

`![Extrait de l'introduction, on voit une crevasse dans le ciel.](les-sous-titres-automatisés-de-youtube.jpg)`

fires the error

> Error: ENOENT: no such file or directory, stat 'src/pages/carnet/2024/20240705.île-de-myst-en-lego/les-sous-titres-automatis%C3%A9s-de-youtube.jpg'

I can live with removing spaces in the images name, it's a bit annoying but OK. However, removing diacritics is more painful: I write in french, a lot of my images have a french name, and an accent on a letter changes its meaning…

Moreover, it seems Eleventy can use accented letters in permalinks with no problem! "île-de-myst-en-lego" is accepted.

Is it something I can do, in configuration for example?

In eleventy.config.js I have

```js
eleventyConfig.addPlugin(eleventyImageTransformPlugin, {
		// File extensions to process in _site folder
		extensions: "html",

		// Output formats for each image.
		formats: ["avif", "webp", "auto"],

		// widths: ["auto"],

		defaultAttributes: {
			// e.g. <img loading decoding> assigned on the HTML tag will override these values.
			loading: "lazy",
			decoding: "async",
		},
	});
```

[ebb-v9-micro.zip](https://github.com/user-attachments/files/17487471/ebb-v9-micro.zip)

Attached is a small version of my project. Download, extract, `npm install` in the folder. Then `npm run build` or `npm run start`, it should fail with the errors I cited. The markdown file is here: `ebb-v9-micro/src/pages/carnet/2024/20240705.île-de-myst-en-lego`, you can comment the images to test.

Thanks a lot!

**Comment by zachleat** [comment]
To be clear, file names with diacritics and spaces are supported as-is. I added passing tests for this to check—without changes to the plugin code.

Looks like your directory name is using combining diacritics and the reference in your markdown code is using a different character:

```
[..."î"].map(char => char.codePointAt(0))
Array [ 238 ]

[..."î"].map(char => char.codePointAt(0))
Array [ 105, 770 ]
```

Make sure you’re using the same filename 😅

**Comment by zachleat** [comment]
Ah, just learned some weird things about Markdown:

```md
[Link](automatisés.jpg)
![Image](automatisés.jpg)
![Image](space in filenames.jpg)
```

outputs

```html
<p><a href="automatis%C3%A9s.jpg">Link</a>
<img src="automatis%C3%A9s.jpg" alt="Image">
![Image](space in filenames.jpg)</p>
```

Workaround is to use HTML directly: `<img src="automatisés.jpg" alt="">` outputs `<img src="automatisés.jpg" alt="">`

**Comment by zachleat** [comment]
I maintain that this is officially a oddity in Markdown specifically! Note that to use spaces in your markdown file references you can use this syntax:

```md
![alt text](<space in filenames.jpg>)
```

**Comment by Lamecarlate** [comment]
Thank you, and sorry again. I'll look forward to v6.0.0.
