### ISSUE TITLE
Persistence of old images in disk cache

### ISSUE THREAD

**Issue by petm5** [11ty/eleventy-img#255]
I'm currently building a site with eleventy-img through a GitHub action that preserves my image output folder between runs to improve build times. Right now that means resized versions of deleted or modified images still end up in the site output.

Is it currently possible to set up eleventy-img such that resized images with a matching hash can be copied from the previous run, but unused images from the previous run don't end up in the site's output?

**Comment by zeroby0** [comment]
Maybe you can add a build hook that removes images with no matching hash. Eleventy, afaik, doesn't have that functionality built-in. If it's in the output folder, it's there till it's deleted.

**Comment by zachleat** [comment]
This could be implemented with an event, we know which images are used on the disk cache—are you using Eleventy or is this request independent of Eleventy?

**Comment by petm5** [comment]
I'm building the site with Eleventy. Probably should have mentioned that earlier.

**Comment by zachleat** [comment]
I believe this is the same request as #131, let’s group up over there!
