### ISSUE TITLE
Is there a way to have this happen for assets in many folders like per post? 

### ISSUE THREAD

**Issue by jacebenson** [11ty/eleventy-img#37]
Is there a way to have this happen for assets in folder.  

Here's the specifics;

https://github.com/jacebenson/jace-ty/tree/main/src/post/my-first-post this is a post folder w/a featured and featured-thumbnail.jpg, if I could generate the featured-thumbnail in the build that would save me a step.

**Comment by zachleat** [comment]
Can you combine https://www.11ty.dev/docs/plugins/image/#creating-an-img-shortcode and the `page` variable? https://www.11ty.dev/docs/data-eleventy-supplied/#page-variable-contents

**Comment by jacebenson** [comment]
Thanks!  I'm not sure this is what I need but it looks like it!
