### ISSUE TITLE
"metadata.format == outputFormat" then "sharpJpegOptions" parameters aren't used

### ISSUE THREAD

**Issue by stephane-klein** [11ty/eleventy-img#39]
My `..eleventy.js` file contains:

```
    ...

    eleventyConfig.addNunjucksAsyncShortcode("image", async function(src, { width }) {
        let stats = await Image(
            src,
            {
                widths: [width],
                formats: ['jpeg'],
                urlPath: "/images/",
                outputDir: "./dist/images/",
                sharpJpegOptions: {
                    quality: 99,
                    progressive: true
                }
            }
        );

        let props = stats['jpeg'].pop();

        return `<img src="${props.url}">`;
    });
    ...
```

When I check output jpeg file with [`magick identify`](https://imagemagick.org/script/identify.php) I see:

```
$  identify -verbose dist/images/7fd33d05-300.jpeg
...
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 80
  Orientation: Undefined
```

The issue: bad quality value, 99 != 80.

When I debug the code, I found that the problem is [here](https://github.com/11ty/eleventy-img/blob/5d6c4daed42dc76c8be347986eb1a2803a846738/img.js#L256)

```
        if(outputFormat && metadata.format !== outputFormat) {
          let sharpFormatOptions = getSharpOptionsForFormat(outputFormat, options);
          sharpInstance.toFormat(outputFormat, sharpFormatOptions);
        }
```

This is this variable value:

- `outputFormat=jpeg`
- ```
   metadata = {
     format: 'jpeg',
     width: 800,
     height: 800,
     space: 'srgb',
     channels: 3,
     depth: 'uchar',
     density: 72,
     chromaSubsampling: '4:4:4',
     isProgressive: false,
     hasProfile: false,
     hasAlpha: false,
     exif=....
   }
   ```

`metadata.format == outputFormat` then `sharpJpegOptions` parameters aren't used.

Question: how can I configure `Quality` option?

**Comment by zachleat** [comment]
A ha yes I’ve verified this one. If the format doesn’t change it doesn’t apply those options. I’ll fix it up

**Comment by zachleat** [comment]
![image](https://user-images.githubusercontent.com/39355/102906970-fbe7da80-443a-11eb-9785-8c1c7488ba00.png)

This will roll up with eleventy-img v0.6.0

**Comment by zachleat** [comment]
v0.6.0 is out!
