### ISSUE TITLE
generateHtml : img tag has an invalid sizes attributes

### ISSUE THREAD

**Issue by seb-celinedesign** [11ty/eleventy-img#42]
generateHtml generate this kind of img tag code : 
`<img src="images.jpeg" width="730" height="792" alt="My image" sizes="
      (min-width: 1280px) 730px,
      (min-width: 1024px) calc((550 + 90 + 90) / (550 + 90 + 90 + 550) * 100vw),
      (min-width: 730px) 730px,
      100vw
    " loading="lazy" decoding="async">`
which is an invalid as the W3C validator says : "The sizes attribute may be specified only if the srcset attribute is also present".

**Comment by neo7-studio-web** [comment]
Yep, I confirm 
![srcset](https://user-images.githubusercontent.com/18073828/103756906-4c049680-5010-11eb-8c24-798df26c4677.jpg)

**Comment by zachleat** [comment]
v0.7.4 has shipped!

**Comment by neo7-studio-web** [comment]
Effective as usual ! Thank you Zach
