### ISSUE TITLE
Keep original image name and then add hash at the end?

### ISSUE THREAD

**Issue by danielLee0721** [11ty/eleventy-img#45]
Found this plugin today. It's great!

I just had one question - is it possible to keep the original image name and add hash to the end?

**Comment by kamituel** [comment]
@danielLee0721  It's supported, yeah:

```js
const path = require("path")

{
   filenameFormat: function (id, src, width, format, options) {
     const extension = path.extname(src)
     const name = path.basename(src, extension)
     return `${name}-${id}-${width}.${format}`
   }
}
```

More about this[ in the documentation.](https://www.11ty.dev/docs/plugins/image/#custom-filenames-new-in-image-0.4.0)

**Comment by danielLee0721** [comment]
Thank you!!
