### ISSUE TITLE
Transparent PNGs probably shouldn't generate JPGs, vice versa

### ISSUE THREAD

**Issue by djmtype** [11ty/eleventy-img#5]
If the original image is a transparent PNG, you most likely wouldn't want JPGs generated, and vice versa.

Is there a smart way to detect this or is it just easier writing 2 separate functions?

**Comment by djmtype** [comment]
I'm closing this issue because I'm blind and overlooked this issue was already recognized. https://github.com/11ty/eleventy-img/issues/2

**Comment by zachleat** [comment]
I hadn't considered this benefit at #2 so I appreciate the issue report!
