### ISSUE TITLE
Only first widths size is generated

### ISSUE THREAD

**Issue by patrickgrey** [11ty/eleventy-img#58]
Hello, I'm using Windows. I have the following code I've copied from Zach's blog (https://www.zachleat.com/web/eleventy-image/):
```javascript
const Image = require("@11ty/eleventy-img");  
(async () => {  
  let stats = await Image("source/photo-1462331940025-496dfbfc7564.jpg", {  
    formats: ["avif", "webp", "jpeg"],  
    widths: [600, 1200, 1800],  
  });  
  console.log(
    Image.generateHTML(stats, {
      alt: "A bomb ass nebula",
      loading: "lazy",
      decoding: "async",
    })
  );
})();
```
When I run `node index.js` only the 600 sized image is generated. That is also the only size output in generateHTML. Is my code wrong please?

**Comment by zachleat** [comment]
What happens when you remove the `formats` key altogether?

**Comment by patrickgrey** [comment]
I get the default jpeg and webp formats at 600w plus this output:
```html
<picture>
  <source type="image/webp" srcset="/img/1789942c-600.webp 600w">
  <img src="/img/1789942c-600.jpeg" width="600" height="569" alt="A bomb ass nebula" loading="lazy" decoding="async">
</picture>
```
Sorry, I should have posted the HTML output in the first post. Doh!

**Comment by zachleat** [comment]
Ah sorry, as noted in the docs this is by design. We “Never upscales raster images larger than original size” unless you’re using SVG as an input file. If you want the larger images you’ll need to get a larger source image!
