### ISSUE TITLE
404 fetches fail not so gracefully

### ISSUE THREAD

**Issue by stedman** [11ty/eleventy-img#6]
I'm using `eleventy-img` to cache avatars from twitter, github, etc. It works great on local but fails on GitHub Pages, bringing down the GitHub Actions deploy.

![npm-build-failure](https://user-images.githubusercontent.com/183122/82493676-f5ad0c80-9aad-11ea-8316-a4c52a97ee10.png)

I'm wondering if there's anything I can do on my end or if [CacheAsset](https://github.com/11ty/eleventy-img/blob/master/img.js#L177) needs a little try/catch (per the [`eleventy-cache-asset` docs](https://github.com/11ty/eleventy-cache-assets#handle-failure-gracefully).

**Comment by stedman** [comment]
I added a try/catch to my shortcode script which solved the problem for me. It now looks something like:

```js
const Image = require('@11ty/eleventy-img');

module.exports = async (src, alt, outputFormat = 'jpeg') => {
  if (alt === undefined) {
    throw new Error(`Missing ALT attribute from: ${src}`);
  }

  try {
    const stats = await Image(src, {
      formats: [outputFormat],
      widths: [null],
    });

    const props = stats[outputFormat].pop();

    return `<img src="${props.outputPath}" alt="${alt}">`;
  } catch (err) {
    console.error(err);

    return '';
  }
};
```

**Comment by stedman** [comment]
### Update

For the sake of brevity in the code block above, I omitted a few settings that may be of interest. Specifically, the `outputDir` is in my distribution directory (`_site`) which is not versioned.

```js
    const stats = await Image(src, {
      formats: [outputFormat],
      urlPath: '/img/',
      outputDir: '_sites/img/`,
      widths: [null],
    });
```
Not sure if makes a diff, but wanted to add it for clarity.

**Comment by stedman** [comment]
### Update

For image caching to work with GitHub Pages and GitHub Actions, I settled for adding `directory: "_cache"` to the [cacheOptions](https://github.com/11ty/eleventy-img#options-list) (available in v0.3.0) and then versioned the `_cache` directory in GitHub. 

Feels dirty but it works for now.

**Comment by zachleat** [comment]
Hmm, what is the best practice around maintaining cache on GitHub pages/actions? On Netlify I use a build plugin to do this

**Comment by stedman** [comment]
Thanks for responding! Your timing is actually quite impeccable. Earlier today I was looking at how you handled the [speedlify](https://github.com/zachleat/speedlify/) caching with Netlify and found a related [GitHub Actions caching solution](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action).

Closing this issue.
