### ISSUE TITLE
Warning about missing `sizes` when necessary per HTML spec

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-img#60]
Short term solution for #59, since adding a new error might break some builds unexpectedly I’d consider that a breaking change.

**Comment by immitsu** [comment]
As I understand it, the only way to check attributes is using `generateHtml` method. And if it is, the warning could be there.
But then there is one more option:  replace the warning by default value. E.g. `sizes=”(min-width: 640px) 60vw, 100vw”`

**Comment by zachleat** [comment]
Closing this as we’ll ship a few small breaking changes in 0.8.0 and this will probably be included.
