### ISSUE TITLE
When using multiple widths, use the largest for [width][height] attributes?

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-img#63]
Perhaps change the default but definitely include an option to do this.

Spawned from test cases and research in https://www.zachleat.com/web/fluid-images/

Pending some feedback on that blog post

**Comment by andeersg** [comment]
Could also be nice to specify a width in the middle. If I want a smaller size for mobiles, and also provide a really large version for big screens but most users get the middle size.

(Maybe specify width attribute, and calculate height based on image format)

**Comment by zachleat** [comment]
What would a `width` in the middle provide?

When used with `width: 100%`, either will work and be fluid width as expected. But when used with the very popular `max-width: 100%`, anything smaller than the largest size in `srcset` will unnecessarily shrink the image in larger containers.

**Comment by andeersg** [comment]
Yeah, that is true, didn't think it through :)

**Comment by zachleat** [comment]
This will ship with 0.8.0!

**Comment by anghelos** [comment]
This isn't great for small images with high dpi versions (like a logo). Especially if the CSS doesn't load for x reason.
Perhaps an option to change this behavior would be useful (#129 ?)
