### ISSUE TITLE
Problem with caching of local files

### ISSUE THREAD

**Issue by MarcL** [11ty/eleventy-img#65]
Hello!

Thanks for Eleventy and this image library. I appear to have a problem with caching local images.
I switched my own thumbnail scripts over to using `eleventy-img` to convert them to smaller files for my site.
I've written an Eleventy shortcode but have also tested the code as a script too.

It seems that if I attempt to convert the same local file twice, the first time it is cached but when it attempts to retrieve the cached version, there's no `jpeg` metadata attached.

Here's some example code for you.

This is the code to convert the image to a specified size which is ultimately called via a shortcode in a liquid template.

```js
const Image = require("@11ty/eleventy-img");

const imageShortcode = async (src, alt, size, className = 'db shadow-4') => {
    if (alt === undefined) {
        throw new Error(`Missing \`alt\` on image from: ${src}`);
    }

    const dataSrc = `./src${src}`;

    let metadata;
    try {
        metadata = await Image(dataSrc, {
            widths: [size],
            formats: ['jpeg'],
            urlPath: '/images/generated/',
            outputDir: './_site/images/generated/'
        });

        if (!metadata) {
            throw new Error(`Couldn't create image metadata for: ${dataSrc}`);
        }
    } catch(error) {
        console.log(error);
        throw error;
    }

    console.log({dataSrc, metadata});
    const data = metadata.jpeg.pop();
    return `<img src="${data.url}" width="${data.width}" alt="${alt}" class="${className}" loading="lazy" decoding="async">`;
};

module.exports = imageShortcode;
```

Here's a test script to convert an image twice.

```js
// Requiring the file above
const imageShortcode = require('../image');

(async () => {
    try {
        const imageName = '/images/banners/404-pineapple.jpg';
        const image1 = await imageShortcode(imageName, 'alt text', 342);
        console.log(image1);
        const image2 = await imageShortcode(imageName, 'alt text', 342);
        console.log(image2);
    } catch(error) {
        console.error('error');
        console.error(error.toString());
    }
})();
```

The output of the above script:

```bash
{ dataSrc: './src/images/banners/404-pineapple.jpg',
  metadata: { jpeg: [ [Object] ] } }
<img src="/images/generated/9819400e-342.jpeg" width="342" alt="alt text" class="db shadow-4" loading="lazy" decoding="async">

{ dataSrc: './src/images/banners/404-pineapple.jpg',
  metadata: { jpeg: [] } }
error
TypeError: Cannot read property 'url' of undefined
```

From the 2nd call, the `jpeg` metadata is an empty array.
Is it user error on my part is or there a bug with the caching of local files?
It could well be the former! 😄 

Thanks,
Marc

**Comment by zachleat** [comment]
Ah, thanks for filing this issue!

Using `metadata.jpeg.pop()` actually mutates the cached entry and removes it! I changed the sample code on the docs to avoid that issue 😅 https://www.11ty.dev/docs/plugins/image/#use-this-in-your-templates

Use `metadata.jpeg[metadata.jpeg.length - 1]` instead so that it isn’t removed.

**Comment by MarcL** [comment]
Doh! That's me just blindly following the example and not thinking about it too. Thanks, @zachleat!

**Comment by trey** [comment]
Yes, thank you, @zachleat (and @MarcL)! I had been reluctant to upgrade eleventy-img because of things like this. Feels good to be on the latest and greatest now!
