### ISSUE TITLE
Post-image generation optimization hooks (e.g. options to add SVGO for SVGs)

### ISSUE THREAD

**Issue by benfrain** [11ty/eleventy-img#67]
First time using this tool (and 11ty!) — apologies if this is obvious but is this supposed to be optimising SVGs? 

I have this outputting what and where I need but is something like SVGO also needed to get SVGs optimised or is there some additional config I have missed?

**Comment by zachleat** [comment]
There is no SVG optimization built in yet!

I could add some programmatic hooks to the utility to allow you to add your own optimizations after we generate the output file. That’d be nice for other formats too I think.

Going to swap this to an enhancement request if that’s okay!

**Comment by benfrain** [comment]
Yes. That’s cool. Just wasn’t sure if it was supposed to be or not. I ended up just running SVGO via npm scripts first before 11ty spins up so all good. But yes, having the ability to do that via this tool would be preferable in the long term, thanks 👍🏻

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-img/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
