### ISSUE TITLE
Changing the outputDir option doesn’t appear to be having an effect on the resulting URL

### ISSUE THREAD

**Issue by hankchizljaw** [11ty/eleventy-img#7]
Thanks for making this plugin, Zach. It’s really, _really_ good! I just noticed this lil’ issue while I was messing around with it. 

## How to reproduce

This is my `Image` instantiation:

```javascript 
    const stats = await Image(`./dist/${src}`, {
      formats: [format],
      widths,
      outputDir: './dist/images/'
    });
```

**Note:** It's set to look in `dist` because I already pre-compress and treat images with a gulp task.

This is a sample of the output:

```javascript
{
  jpeg: [
    {
      format: 'jpeg',
      width: 320,
      height: 216,
      url: '/img/121af431-320.jpeg',
      sourceType: 'image/jpeg',
      srcset: '/img/121af431-320.jpeg 320w',
      outputPath: 'dist/images/121af431-320.jpeg',
      size: 16523
    },
    {
      format: 'jpeg',
      width: 600,
      height: 406,
      url: '/img/121af431-600.jpeg',
      sourceType: 'image/jpeg',
      srcset: '/img/121af431-600.jpeg 600w',
      outputPath: 'dist/images/121af431-600.jpeg',
      size: 46880
    },
    {
      format: 'jpeg',
      width: 1600,
      height: 1082,
      url: '/img/121af431.jpeg',
      sourceType: 'image/jpeg',
      srcset: '/img/121af431.jpeg 1600w',
      outputPath: 'dist/images/121af431.jpeg',
      size: 149347
    }
  ];
}

```

**Comment by hankchizljaw** [comment]
I've had a little dig around and I reckon it's around here that the option needs to be accounted for: https://github.com/11ty/eleventy-img/blob/master/img.js#L145

I can do a PR if you want?

**Comment by stedman** [comment]
@hankchizljaw I had a similar issue and was able to fix it by setting the `urlPath` option. In your case, I think it would be `urlPath: '/images/'`.

Perhaps this is an easy docs update to clarify?

**Comment by hankchizljaw** [comment]
@stedman, you’re a diamond—that worked perfectly. Thank you!

**Comment by zachleat** [comment]
Happy to entertain a PR! But yes if you change `outputDir` you will also want to set `urlPath`
