### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by ivanov-v** [11ty/eleventy-img#80]
Hello. Is it possible to add support for retina images?

For example:
`<source type="image/jpeg" srcset="/assets/images/office-photos/entry-1-preview-2x.jpeg 2x">`

**Comment by paulogr** [comment]
I have the same question without an answer.

Someone can help us?

**Comment by tobystokes** [comment]
You can just add in extra widths and let the browsers do the maths.
For instance, if you specify widths of `[800, 1600,2400]` a 2x retina browser will know to pick 1600px wide image as src when showing at 800 device pixels.

**Comment by zachleat** [comment]
@tobystokes is right. While `Image.generateHTML` doesn’t use the `1x` `2x` syntax, the browser will use the `w` unit images to select the appropriate image (retina or no) for the dimensions and DPI of the screen. Just make sure you use the `sizes` attribute too

Sample:
```html
<img alt="My alt text" src="/img/KkPMmHd3hP-300.jpeg" width="600" height="399" srcset="/img/KkPMmHd3hP-300.jpeg 300w, /img/KkPMmHd3hP-600.jpeg 600w" sizes="100vw">
```

**Comment by nachtfunke** [comment]
I must say I find this also an unsolved issue. Usually, when setting high-resolution versions of an image we can just provide multiple versions with the `x` descriptor. The `w` descriptor does not do the same thing as the `x` descriptor.

I also wish there was more explicit documentation for this specific use case. I would like to just use eleventy image to provide multiple resolutions of the same image but I literally just do not know how, without having to use `eleventy:ignore` and do it manually anyway. This may all be documented somehow but I must say it really just eludes me entirely. Even if I set multiple `sizes` in my image, the transform just outputs a single image in `srcset`, so I just really don't understand how to solve this use case with eleventy image at all.

**Comment by IlyaCedrik** [comment]
I ran into the same problem and eventually decided to use a shortcode.

```js
const fileExistsCache = new Map();
  
eleventyConfig.addShortcode("imageWithRetina", async function (src, alt, width, height) {
  if (src.toLowerCase().endsWith('.svg')) {
    return `<img src="${src}" alt="${alt}" width="${width}" height="${height}" loading="lazy">`;
  }
  
  const srcPath = src.startsWith('/') ? `src${src}` : src;
  const retinaSrcPath = srcPath.replace(/(\.[^.]+)$/, '@2x$1');
  
  let hasRetinaVersion = fileExistsCache.get(retinaSrcPath);
  if (hasRetinaVersion === undefined) {
    const fs = await import('fs');
    hasRetinaVersion = fs.existsSync(retinaSrcPath);
    fileExistsCache.set(retinaSrcPath, hasRetinaVersion);
  }
  
  const imageOptions = {
    formats: ["webp", "png"],
    outputDir: "./dist/img/",
    urlPath: "/img/",
  };
  
  if (hasRetinaVersion) {
    const [normalImage, retinaImage] = await Promise.all([
      Image(srcPath, { ...imageOptions, widths: [width] }),
      Image(retinaSrcPath, { ...imageOptions, widths: [width * 2] })
    ]);
    
    const normalWebp = normalImage.webp?.[0]?.url || normalImage.png[0].url;
    const normalFallback = normalImage.png[0].url;
    const retinaWebp = retinaImage.webp?.[0]?.url || retinaImage.png[0].url;
    const retinaFallback = retinaImage.png[0].url;
    
    return `<picture>
      <source srcset="${normalWebp} 1x, ${retinaWebp} 2x" type="image/webp">
      <img src="${normalFallback}" srcset="${normalFallback} 1x, ${retinaFallback} 2x" alt="${alt}" width="${width}" height="${height}" loading="lazy" decoding="async">
    </picture>`;
  }

  return Image(srcPath, {
    ...imageOptions,
    widths: [width],
    returnType: "html",
    htmlOptions: {
      imgAttributes: {
        alt,
        width: width.toString(),
        height: height.toString(),
        loading: "lazy",
        decoding: "async",
      }
    }
  });
});
```

**Comment by teddybradford** [comment]
> While `Image.generateHTML` doesn’t use the `1x` `2x` syntax, the browser will use the `w` unit images to select the appropriate image (retina or no) for the dimensions and DPI of the screen. Just make sure you use the `sizes` attribute too

@zachleat It seems setting explicit width/height attributes on an `<img>` disables the srcset attribute from being generated for that image tag. Is there an example somewhere for how to process, say, a 2000x1000px image so that it's final width/height are 500 and 250 respectively with the image transform src at 1000x500px so that it looks crisp on high-DPI screens?

In other words, is there a way to get output that effectively achieves something like `<img src="/.11ty/image/?src=image.png&width=1000&format=webp&via=transform" width="500" height="250">`
