### ISSUE TITLE
Use shortcode inside a included block? 

### ISSUE THREAD

**Issue by Okkido** [11ty/eleventy-img#81]
I'm using Nunjucks with Front Matter to create a simple page builder.

My `page.njk` include "blocks" like this:

```
{% for block in blocks %}
  {% include "blocks" + "/" + block.template + ".njk" %}
{% endfor %}
```

And my Front Matter for a page with blocks:

```
---
title: "Page title"
blocks:
- template: image
  image: "/images/laura-davidson-qbah4ildazy-unsplash.jpg"
- template: another-block
...
---
```

The end gold is to use a shortcode to render an image using eleventy-img. But when I add the image shortcode Nunjucks stops rendering my block. No errors, nothing. It doesn't matter if I use a hardcoded image like:
```{% image "assets/images/photo.png", "Alt <3 11ty" %}``` (that shortcode works fine outside of my block) or if i try to use image data from Front Matter.
Other shortcodes work fine.

Are there a limitation in using the image shortcode this way?

**Comment by kodeFant** [comment]
I had a similar issue, but the include was inside  {% if (...) %} {% endif %}. The image shortcode worked without that if. Luckily the if was redundant for that include anyway. 

I had something like this that didn't work because it was inside the if:

```njk
{% set postslist = collections | series (series) | reverse %}
{% set postListLength = postslist | length %}
{% if postListLength > 0 %}
<h3 class="text-3xl my-4 font-bold">This article belongs to a {{postListLength}} part series</h3>
{% include "postslist.njk" %}
{% endif %}
```

Not sure if there's a connection to your issue, but figured I might share my experience just in case.

**Comment by maeligg** [comment]
I just ran into the same issue, also with an include. My workaround for now has been to move the markup from my include inside my other template, where it works fine. Strange issue.

**Comment by StevenPate** [comment]
I ran into the same problem. Not being able to put the shortcode in partials the way I would typically use them has meant some duplicated code. I haven't found another solution.

**Comment by arnaudlimbourg** [comment]
Encountered the same issue. I have layout -> include -> include with the image shortcode in this last include and it does not work. I haven't been able to find out why so far.

**Comment by phillipplum** [comment]
Hello everyone, I have or had the same problem. I suspect it is because you are trying to make this async and it does not work with an include.

Here is the information on how to make a synchronous call: https://www.11ty.dev/docs/plugins/image/#synchronous-usage

After switching from async to synchronous it works.

**Comment by maeligg** [comment]
Good catch ! Indeed it works if you use the plugin synchronously. I wonder if this a limitation with elevent-img specifically or if all shortcodes work that way ? The doc would benefit from a warning on this, imo.

**Comment by phillipplum** [comment]
You just have to make sure that the images are generated anyway, because the images are not generated when you make a synchronous call.
This currently means that I get warnings in the console that files were not found, but the result is still correct.

**Comment by architchandra** [comment]
I'm facing the same issue. I _include_ various components like image, text, etc. The _async_ shortcode is not working if I include a component, but it is if I place the custom tag directly in the template. 

Interestingly, if I have both the include statement and the custom tag present in the template (as seen in the template code below), two images show up—the custom tag in both the included template and the main template work.
```
{% set imageParams = {
  image: banner.image,
  altText: banner.altText,
  caption: banner.caption
} %}
{% include 'components/image.njk' %}
{% image banner.image, 'yaya', 'toure' %}
```

**Comment by zachleat** [comment]
I will note that a bug of fixes for Nunjucks async shortcodes went into 1.0, which released after this issue was opened. Notably https://github.com/11ty/eleventy/issues/1053 https://github.com/11ty/eleventy/pull/1749 and https://github.com/11ty/eleventy/issues/2140

**Comment by zachleat** [comment]
Just confirmed locally that async image shortcodes work inside of an include in Nunjucks in Eleventy 1.0.
