### ISSUE TITLE
Escape attributes passed to HTML generator

### ISSUE THREAD

**Issue by delucis** [11ty/eleventy-img#82]
Would it be beyond the scope of this plugin to escape the attributes passed to `Image.generateHTML`?

Currently unescaped attributes result in mangled HTML output:

```js
Image.generateHTML(stats, {
  alt: 'Some "unescaped" user content',
});
```

```html
<!-- Output -->
<img src="/img.png" alt="Some "unescaped" user content" />
```

This is pretty simple to solve by dropping in an attribute escaping library of one’s choice before passing attributes to `generateHTML`, but I wondered if it would be a good idea to do this by default? Are there any attributes that `generateHTML` *shouldn’t* escape?

**Comment by zachleat** [comment]
This will ship with Eleventy Image v3.0.0
