### ISSUE TITLE
Plugin greatly increases Eleventy startup time

### ISSUE THREAD

**Issue by autumnlansing** [11ty/eleventy-img#87]
Use of this plugin has greatly increased start-up time for Eleventy. I've created four different shortcodes for use with different types of images on a site, and my start-up time has increased from a few seconds to almost five minutes. This occurs with both async and sync functions.

Eleventy takes forever to write files when it starts, whereas without this plugin it writes files immediately. This site is not a large one, only about 20 pages and 24 images. Once Eleventy has built the site after startup, however, it runs normally. Post-startup builds happen in a few seconds. It's only at startup that it seems to hang. Is there anyway to mitigate this problem?

**Comment by autumnlansing** [comment]
Having had a chance to spend some time on this over the weekend, I see that the plugin is rebuilding every single image when Eleventy starts, and there doesn't seem to be any way around it. Removing a source image causes the build to fail. The source image has to be there, and the plugin will rebuild each image every time it starts, as it only has an in-memory cache. That can turn into a huge cost of time for any site with more than a few images. A possible solution would be to implement a persistent cache, perhaps in the form of a json file.

**Comment by Princesseuh** [comment]
This is kinda a duplicate of https://github.com/11ty/eleventy-img/issues/51

**Comment by autumnlansing** [comment]
Yes, thank you. I didn't see that issue when I first opened this one, as the title didn't seem similar enough to what I thought was wrong. I'll close this one. :)
