### ISSUE TITLE
AVIF images are broken in Chrome Canary

### ISSUE THREAD

**Issue by kamituel** [11ty/eleventy-img#91]
AVIF files generated by eleventy-img are not working in recent Chrome Canary.

The [underlying issue is with libheif](https://github.com/strukturag/libheif/issues/477), used by sharp, used by eleventy-img. 

I've raised related issues with [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1198455) and with [sharp](https://github.com/lovell/sharp/issues/2666) recently. 

Opening one here as well so that maintainers are aware of the issue and will know to update sharp dependency as soon as the fixed version is released.

**Comment by zachleat** [comment]
Awesome, thank you!

**Comment by zachleat** [comment]
Also reported via Twitter https://twitter.com/freshyill/status/1390419540610363393

Progress was made today https://github.com/lovell/sharp/issues/2666

**Comment by zachleat** [comment]
Per https://github.com/lovell/sharp/issues/2666#issuecomment-846393953 this has been downgraded from a break-the-web emergency 😅

**Comment by jaredgorski** [comment]
Seen in Chrome Dev.

**Comment by zachleat** [comment]
@jaredgorski where at?

**Comment by jaredgorski** [comment]
@zachleat I migrated part of my personal site to use `eleventy-img` yesterday and it was working on every browser I tried until this morning when I logged into Chrome Dev (on my work machine) and checked to see if it's working here as well. I opened https://jaredgorski.org/writing/13-we-bought-an-old-truck on Chrome Dev (updated to latest) and I see `alt` text. Accessing the asset directly doesn't result in a download, but rather this:

<img width="1792" alt="Screen Shot 2021-08-02 at 10 58 47 AM" src="https://user-images.githubusercontent.com/36674760/127904148-1b50a8e2-91a3-4ba9-a485-9924776a4297.png">

According to my cursory research into these issues on Chrome Canary, the behavior I'm seeing on Chrome Dev matches. Figured I'd mention it here in case this comes as a surprise.

**Comment by zachleat** [comment]
Yeah, I appreciate it. I’m eyeing this very closely. There are a bunch of broken images currently in Canary on the https://www.11ty.dev/ home page. I believe these were generated with an old version of `sharp`/`eleventy-img` and were checked into the repo? Not 100% sure. I was able to regenerate all of the Built With Eleventy avatars in the latest versions and those are working fine.

Can you try to regenerate your images with the newest versions?

**Comment by jaredgorski** [comment]
@zachleat Very interesting; the avatars are all broken in Chrome Dev `Version 94.0.4590.0 (Official Build) dev (x86_64)`.

<img width="1792" alt="Screen Shot 2021-08-02 at 11 16 13 AM" src="https://user-images.githubusercontent.com/36674760/127905872-4c3ed16d-d8fb-4c2b-8c96-915146d855ff.png">

I'm using `eleventy-img 0.9.0` on my site, but I can regenerate (after work today) and report back here with results.

I'm unsure of the relationship between Canary and Dev in terms of releases, but I wouldn't be surprised if Dev gets Canary code.

**Comment by GrimLink** [comment]
I can confirm this issue also exists on the Beta version as of Chrome 93.
I am also using the latest version of `eleventy-img` (0.9.0).
In the issue on https://bugs.chromium.org/p/chromium/issues/detail?id=1198455#c28 it is also noted that this back as per this version do the 'pixi' box requirement.

**Comment by jackysee** [comment]
I'm using Firefox Nightly, the newly generated avif is also broken. 
Even worse, Firefox cannot fallback to other format in the `<picture>` tag.

**Comment by zachleat** [comment]
Shipped with `sharp` v0.29.0 https://github.com/lovell/sharp/issues/2666

**Comment by zachleat** [comment]
Shipping with `@11ty/eleventy-img` v0.10.0

**Comment by zachleat** [comment]
Per actions failure https://github.com/11ty/eleventy-img/actions/runs/1143536646 this also needs #100.
