### ISSUE TITLE
Output images seem partially processed.

### ISSUE THREAD

**Issue by patrickgrey** [11ty/eleventy-img#95]
An example of the problem can be seen in this image:

![Screenshot 2021-05-07 161540](https://user-images.githubusercontent.com/1609799/117471655-028d6f00-af50-11eb-9370-8a9ce88ee1ed.png)

Has anyone experienced this before? It is happening with all formats (jpg, avif, webp). HTML output, number of output images and formats are correct. No error messages. Original images are larger than largest output size. I've tried a number of different source images (all jpg).

Is this likely to be a problem with the sharp processor? I can't find other examples online.

**Comment by zachleat** [comment]
Are you using the `sync` or `async` method?

**Comment by patrickgrey** [comment]
`sync`
Sorry, I should have included some code:
```
function imageShortcode(src, alt, cls, sizes, widths, formats) {
  if (!alt) {
    throw new Error(`Missing \`alt\` on image from: ${src}`);
  }

  const imagePath = path.dirname(src);
  const urlPath = imagePath + "/";
  const outputDir = "./" + publish + this.page.url + imagePath + "/";
  const imageSource = "./" + publish + this.page.url + src;

  const sizesString = sizes || `(max-width: 2400px) 100vw, 2400px`;

  let options = {
    widths: widths || [320, 640, 960, 1200, 1800, 2400],
    formats: formats || ["avif", "webp", "jpeg"],
    urlPath: urlPath,
    outputDir: outputDir,
  };

  // generate images, while this is async we don’t wait
  Image(imageSource, options);

  let imageAttributes = {
    class: cls || "",
    alt,
    sizes: sizesString,
    loading: "lazy",
    // decoding: "async",
  };
  // get metadata even the images are not fully generated
  metadata = Image.statsSync(imageSource, options);
  
  const html = Image.generateHTML(metadata, imageAttributes);
  
  return html;
}
```

```
module.exports = function (eleventyConfig) {
  eleventyConfig.addNunjucksShortcode("image", imageShortcode);
}

**Comment by patrickgrey** [comment]
OK, I think I'm getting somewhere. I changed the shortcode to use `async` but the issue persists.

I noticed a pattern to the problem. When I start the dev server the image is processed properly every time. It's only on file changes while the server is already running that the corrupted image files appear.

This makes me think it's perhaps a race condition. I'm using 11ty, postcss, tailwind, and rollup in my setup. I'll build a simplified repo and add in features as I go to see when it is replicated. I'm going to close now as I don't think this is directly related to the plugin.

**Comment by patrickgrey** [comment]
Yup, just confirming the cause was a cockup. If you look at the code above 

`const imageSource = "./" + publish + this.page.url + src;`

I had passthroughcopy for all images. The code should refer to my source folder for input instead of the publish folder - so 

``const imageSource = "./" + source + this.page.url + src;``

**Comment by zachleat** [comment]
Really appreciate the follow up—thank you!
