### ISSUE TITLE
Only some of the images are outputted in the configured widths

### ISSUE THREAD

**Issue by maeligg** [11ty/eleventy-img#96]
Hello,

I'm using the plugin with the `generateHTML` function and using a Nunjucks shortcode, something very close to the default config. My metadata block looks something like this : 
```
let metadata = await Image(`./src/images/${src}.jpg`, {
    widths: [600, 3000],
    formats: ['webp', 'jpeg'],
    outputDir: './dist/images',
    urlPath: '/images/'
});
```

When I run this, most of my images are outputted in 600px width and 3000px width in both jpeg and webp, but a couple ones are only outputted in 600px width (both jpeg and webp). If I use this config for the width instead : `widths: [3000]`, then most of the images are outputted in 3000px width, but a couple again (the same ones) are outputted only in 1355px width. Any idea what could cause this ? I initially thought some of the source image files might be corrupt, but what I find strange is that they are still processed and outputted, just not in the configured widths.

**Comment by Alexs7zzh** [comment]
I don't think eleventy-img upscales images. Can you check if the original widths of the images are all above 3000px?

**Comment by maeligg** [comment]
Oh ofc 🤦‍♂️ I just assumed they all had the same size but didn't actually check. Makes sense, sorry for the trouble !
