### ISSUE TITLE
How do I add a custom class?

### ISSUE THREAD

**Issue by sabelapaulo** [11ty/eleventy-img#97]
It can be useful to add custom classes to images when using Tailwind. The problem is I don't know how to do that with eleventy-img!

`.eleventy.js`:

```const Image = require("@11ty/eleventy-img");

async function imageShortcode(src, alt, sizes) {
  let metadata = await Image(src, {
    widths: [300, 600],
    formats: ["avif", "jpeg"]
    urlPath: "./img",
    outputDir: "./_site/img/"
  });

  let imageAttributes = {
    alt,
    sizes,
    loading: "lazy",
    decoding: "async",
  };

  // You bet we throw an error on missing alt in `imageAttributes` (alt="" works okay)
  return Image.generateHTML(metadata, imageAttributes);
}

module.exports = function(eleventyConfig) {
  eleventyConfig.addNunjucksAsyncShortcode("image", imageShortcode);
  eleventyConfig.addLiquidShortcode("image", imageShortcode);
  eleventyConfig.addJavaScriptFunction("image", imageShortcode);
};
```

And in my template:

```{% image "./img/cat.jpg", "photo of my cat", "100vw" %}```

Does anyone know how I can modify the above `.eleventy.js` so that I can pass along some optional class(es)?

For example I'm looking to do something like this:
```{% image "./img/cat.jpg", "my-custom-class h-20 w-20", "photo of my cat", "100vw" %}```

Something like that. Is this possible?

**Comment by immitsu** [comment]
In imageShortcode you can pass any arguments you want. And then in return statement use string template for needed tag/tags description instead of the util. Like `<picture>..<img class=${myClass}../> ..</picture>`

**Comment by Brixy** [comment]
Hi,

this is what I use for `return`:

```
return `<figure${attributes ? ` ${attributes}` : ""}>${Image.generateHTML(metadata, imageAttributes)}${figcaption ? `<figcaption>${figcaption}</figcaption>` : ""}</figure>`;
```

It’s a very flexible solution—I hope—because you can use anything for attributes, e.g.

```
{% image "./img/cat.jpg", "photo of my cat", "data-xy=\"test\" style=\"width: 50%\" class=\"test\"" %}
```

**Comment by sabelapaulo** [comment]
Here is what I have:

```
async function imageShortcode(classes, src, alt, sizes = "100vw") {
  if(alt === undefined) {
    // You bet we throw an error on missing alt (alt="" works okay)
    throw new Error(`Missing \`alt\` on responsiveimage from: ${src}`);
  }

  let metadata = await Image(src, {
    widths: [300, 600],
    formats: ['avif', 'webp', 'jpeg'],
    urlPath: "./img",
    outputDir: "./_site/img/"
  });

  let lowsrc = metadata.jpeg[0];

  return `<picture class=${classes}>
    ${Object.values(metadata).map(imageFormat => {
      return `  <source type="${imageFormat[0].sourceType}" srcset="${imageFormat.map(entry => entry.srcset).join(", ")}" sizes="${sizes}">`;
    }).join("\n")}
      <img
        src="${lowsrc.url}"
        width="${lowsrc.width}"
        height="${lowsrc.height}"
        alt="${alt}"
        loading="lazy"
        decoding="async">
    </picture>`;
}
```
And I can use a picture in the template like this:

`{% image "mx-auto block", "./img/cat.jpg", "photo of my cat", "100vw" %}`

But there is an issue! It comes out like: `<picture class="mx-auto" block ...>`

How can I get it to accept two or more classes in this way?

**Comment by immitsu** [comment]
@sabelapaulo You can try to put the class attribute in quotation marks. Or pass needed classes as array of strings and then join

**Comment by kenci** [comment]
> It can be useful to add custom classes to images when using Tailwind. The problem is I don't know how to do that with eleventy-img!
> 
> `.eleventy.js`:
> 
> ```
> 
> async function imageShortcode(src, alt, sizes) {
>   let metadata = await Image(src, {
>     widths: [300, 600],
>     formats: ["avif", "jpeg"]
>     urlPath: "./img",
>     outputDir: "./_site/img/"
>   });
> 
>   let imageAttributes = {
>     alt,
>     sizes,
>     loading: "lazy",
>     decoding: "async",
>   };
> 
>   // You bet we throw an error on missing alt in `imageAttributes` (alt="" works okay)
>   return Image.generateHTML(metadata, imageAttributes);
> }
> 
> module.exports = function(eleventyConfig) {
>   eleventyConfig.addNunjucksAsyncShortcode("image", imageShortcode);
>   eleventyConfig.addLiquidShortcode("image", imageShortcode);
>   eleventyConfig.addJavaScriptFunction("image", imageShortcode);
> };
> ```
> 
> And in my template:
> 
> `{% image "./img/cat.jpg", "photo of my cat", "100vw" %}`
> 
> Does anyone know how I can modify the above `.eleventy.js` so that I can pass along some optional class(es)?
> 
> For example I'm looking to do something like this:
> `{% image "./img/cat.jpg", "my-custom-class h-20 w-20", "photo of my cat", "100vw" %}`
> 
> Something like that. Is this possible?

maybe this should do it:
 `.eleventy.js`:
 
 ```
 
 async function imageShortcode(src, alt, css, sizes) {
   let metadata = await Image(src, {
     widths: [300, 600],
     formats: ["avif", "jpeg"]
     urlPath: "./img",
     outputDir: "./_site/img/"
   });
 
   let imageAttributes = {
    class: css,
     alt,
     sizes,
     loading: "lazy",
     decoding: "async",
   };
```

and then use it as you wanted to:
`{% image "./img/cat.jpg", "photo of my cat",  "my-custom-class h-20 w-20", "100vw" %}`

**Comment by zachleat** [comment]
I believe @immitsu isolated the issue here, it should be:

```diff-js
- return `<picture class=${classes}>
+ return `<picture class="${classes}">
```

Thanks y’all!

**Comment by inetbiz** [comment]
@zachleat question about loading lazy. That should be called ONLY when outside of the top-fold viewport, right? https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading So, images that are within the initial viewport should not have loading lazy?

**Comment by agarzola** [comment]
That is typically what you would want, yes. If you want to be more explicit, you can pass in `loading: 'eager'` for images that should be fetched immediately.

**Comment by inetbiz** [comment]
> Here is what I have:
> 
> ```
> async function imageShortcode(classes, src, alt, sizes = "100vw") {
>   if(alt === undefined) {
>     // You bet we throw an error on missing alt (alt="" works okay)
>     throw new Error(`Missing \`alt\` on responsiveimage from: ${src}`);
>   }
> 
>   let metadata = await Image(src, {
>     widths: [300, 600],
>     formats: ['avif', 'webp', 'jpeg'],
>     urlPath: "./img",
>     outputDir: "./_site/img/"
>   });
> 
>   let lowsrc = metadata.jpeg[0];
> 
>   return `<picture class=${classes}>
>     ${Object.values(metadata).map(imageFormat => {
>       return `  <source type="${imageFormat[0].sourceType}" srcset="${imageFormat.map(entry => entry.srcset).join(", ")}" sizes="${sizes}">`;
>     }).join("\n")}
>       <img
>         src="${lowsrc.url}"
>         width="${lowsrc.width}"
>         height="${lowsrc.height}"
>         alt="${alt}"
>         loading="lazy"
>         decoding="async">
>     </picture>`;
> }
> ```
> 
> And I can use a picture in the template like this:
> 
> `{% image "mx-auto block", "./img/cat.jpg", "photo of my cat", "100vw" %}`
> 
> But there is an issue! It comes out like: `<picture class="mx-auto" block ...>`
> 
> How can I get it to accept two or more classes in this way?

What's the rest of the code?

**Comment by adamduncan** [comment]
To the point of this original ticket: Do we think that there's a world where we extend the `Image` API's surface area to include a `className` option as part of the `globalOptions` argument?

I'd see this as a pretty common use-case, and potentially a fairly uncontroversial addition? Seems such a shame to have to break off and essentially reimplement all of the great stuff that's already in the `generateHTML` method in user-land, just to tack on one extra attribute.

What do you think?
